name: LINS
version: "0.6"
date: 2023-11-29
description: |
    provides an algorithm for computing the normal subgroups of a finitely presented group up to some given index bound.

authors:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

maintainers:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

GAP: ">= 4.11"

www: https://FriedrichRober.github.io/LINS/
readme: README.md
packageinfo: https://FriedrichRober.github.io/LINS/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/FriedrichRober/LINS/releases/download/v0.6/LINS-0.6.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Rob23</span>]   <b class='BibAuthor'>Rober, F.</b>,
     <i class='BibTitle'>LINS, provides an algorithm for computing the normal subgroups of a finitely presented group up to some given index bound.,
             Version 0.6</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://FriedrichRober.github.io/LINS/">https://FriedrichRober.github.io/LINS/</a></span>.
    </p>
    

bibtex: |
    @misc{ LINS0.6,
      author =           {Rober, F.},
      title =            {{LINS}, provides an algorithm for computing the normal
                          subgroups  of  a  finitely  presented group up to some
                          given index bound., {V}ersion 0.6},
      month =            {Nov},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href         {https://FriedrichRober.github.io/LINS/}
                          {\texttt{https://FriedrichRober.github.io/}\discretionary
                          {}{}{}\texttt{LINS/}}},
      printedkey =       {Rob23}
    }

